custom dte

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,38 +1,99 @@
+name: CI
 on:
   push:
-    branches-ignore:
-      - 'release/**'
-      - 'hotfix/**'
-      - 'main'
+    branches:
+      - main
+  pull_request:
 
+# Needed for nx-set-shas when run on the main branch
 permissions:
-  contents: read
   actions: read
-  id-token: write
+  contents: read
 
 jobs:
-  test:
-    name: Test
+  main:
+    name: Nx Cloud - Main Job
     runs-on: ubuntu-latest
-    timeout-minutes: 15
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
+        name: Checkout [Pull Request]
+        if: ${{ github.event_name == 'pull_request' }}
         with:
+          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
+          ref: ${{ github.event.pull_request.head.sha }}
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
           fetch-depth: 0
 
-      # Cache node_modules
-      - uses: actions/setup-node@v4
+      - uses: actions/checkout@v4
+        name: Checkout [Default Branch]
+        if: ${{ github.event_name != 'pull_request' }}
+        with:
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+          fetch-depth: 0
+
+      - name: Use the package manager cache if available
+        uses: actions/setup-node@v3
         with:
           node-version: 20
           cache: 'npm'
 
-      - run: npm ci --legacy-peer-deps
-      - run: npx playwright install
+      - name: Install dependencies
+        run: npm ci
 
-      - uses: nrwl/nx-set-shas@v4
+      - name: Check out the default branch
+        run: git branch --track main origin/main
 
-      - name: Run lint, test and sonar scan
+      - name: Initialize the Nx Cloud distributed CI run and stop agents when the build tasks are done
+        run: npx nx-cloud start-ci-run --distribute-on="manual" --stop-agents-after=e2e-ci
+
+      - name: Run commands in parallel
         run: |
-          npx nx affected -t lint test e2e -c ci
+          # initialize an array to store process IDs (PIDs)
+          pids=()
+
+          # function to run commands and store the PID
+          function run_command() {
+            local command=$1
+            $command &  # run the command in the background
+            pids+=($!)  # store the PID of the background process
+          }
+
+          # list of commands to be run on main has env flag NX_CLOUD_DISTRIBUTED_EXECUTION set to false
+          run_command "NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- nx format:check"
+
+          # list of commands to be run on agents
+          run_command "npx nx affected -t lint,test,build,e2e-ci --parallel=3"
+
+          # wait for all background processes to finish
+          for pid in ${pids[*]}; do
+            if ! wait $pid; then
+              exit 1  # exit with an error status if any process fails
+            fi
+          done
+
+          exit 0 # exits with success status if a all processes complete successfully
+
+  agents:
+    name: Agent ${{ matrix.agent }}
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        # Add more agents here as your repository expands
+        agent: [1, 2, 3]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Use the package manager cache if available
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+          cache: 'npm'
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Start Nx Agent ${{ matrix.agent }}
+        run: npx nx-cloud start-agent
+        env:
+          NX_AGENT_NAME: ${{ matrix.agent }}
